### ISSUE TITLE
Cannot Login with UPN format

### ISSUE THREAD

**Issue by rbeghin** [DNNCommunity/DNN.ActiveDirectory#12]
Previous versions of the module allowed users to login with UPN format (user@domain.com). Is this functionality still available with version 6?

**Comment by sawest** [comment]
I dont believe that go changed.  Are you experiencing issues using UPN?

**Comment by rbeghin** [comment]
Yes. I can get login to work as domain\user or by setting Default Domain as just user. However, I cannot get user@domain.com to work.

**Comment by sawest** [comment]
#14 
Pull request was made and new release uploaded.  Install update 6.0.2 and see if issue is resolved.

**Comment by sawest** [comment]
@rbeghin 
Any feedback on this?  Wanted to wait on your verification before closing issue.

**Comment by rbeghin** [comment]
sorry I've been away from this project. I'll send an update an a couple of days or so. Thanks,

**Comment by rbeghin** [comment]
I installed 6.0.2 and I can now login using UPN format. However, if a user had previously logged in the system creates and additional user which looks the same BUT the roles do not seem to have been applied to the new UPN logon.

Example: user1 previously logged in and was added as a user domain\user1. user1 was given the Administrator role. AFTER the update to 6.0.2 I can still logon as user1 or domain\user1 AND I can logon as user1@domain.com however now an additional user has been created as domain\user1 and the new user is not a member of the Administrator role.

One additional thing, there might be a problem with the installer package. I installed the package assuming that it was an upgrade. It did not upgrade and instead 6.0.0 was still there with an option to delete. Version 6.0.2 appears as another extension BUT it does not have a delete option. I thought maybe there was a problem with the extension installation so I deleted 6.0.0 and then I re-installed 6.0.2 and now I have two versions of 6.0.2 showing as installed. But that said the module is authenticating AD.

**Comment by rbeghin** [comment]
Additional problem: after disabling Default Domain in AD's Site Settings, logging in using UPN format no longer works.

**Comment by sawest** [comment]
#24 Duplicate issue

**Comment by sawest** [comment]
fixed in pull request #27
